const axios = require("axios");
const RESPONSE_API_URL = "http://127.0.0.1:5002/translate"; // Endpoint for response generated by Tranformer

async function translateResponse(query) {
    try {const pythonResponse = await axios.post(RESPONSE_API_URL, { sentence: query });
    const {translation} = pythonResponse.data; // Extract both fields
    return {translation} ; // Return an object with both values
    } catch (error) {
        console.error("Error in transformer model:", error);
        return "Sorry, I couldn't translate the response.";
    }
}


module.exports = { translateResponse };
