const axios = require("axios");
const RESPONSE_API_URL = "http://127.0.0.1:5001/api/classify"; // Endpoint for response generated by Tranformer

async function processCategory(query) {
    try {const pythonResponse = await axios.post(RESPONSE_API_URL, { query });
    const { category} = pythonResponse.data; // Extract both fields
    return { category} ; // Return an object with both values
    } catch (error) {
        console.error("Error in transformer model:", error);
        return "Sorry, I couldn't process that query.";
    }
}


module.exports = { processCategory };
